version: 1.0.0.{build}

image: Visual Studio 2022

configuration: Debug
skip_tags: true

before_build:
- ps: dotnet --info
- ps: dotnet restore -v Minimal

build_script:
- ps: dotnet build --no-restore -c $Env:CONFIGURATION

test_script:
- ps: dotnet test --no-build -c $Env:CONFIGURATION
