version: 1.0.0.{build}

image: Visual Studio 2019

configuration: Debug
skip_tags: true

services:
 - mssql2017
 - mysql
 - postgresql101

before_build:
- ps: dotnet --info
- ps: dotnet restore -v Minimal

build_script:
- ps: dotnet build -c $Env:CONFIGURATION

test_script:
- ps: dotnet test -c $Env:CONFIGURATION
